### PR TITLE
up version aws-java-sdk to 1.11.525

### PR DESCRIPTION
**Pull request by marioja**
This will provide new regions (amongst other things) that were not available as of 1.10.68

### CODE REVIEW

**Comment by marioja** [comment]
Will you create version 1.5.1 artifact on maven central?

**Comment by aldrinleal** [comment]
Uploading. Since I haven't released anything in the past 3 years, I'm dusting off some small details :)

image

**Comment by marioja** [comment]
R u suggesting that on my account you are back at it? Wow I’m impressed.  Actually there is something else I think would be greatly useful to do if I may suggest. I could open an issue but unfortunately would not have the time to do a pull request

**Comment by marioja** [comment]
It has to do with authenticating proxy support

**Comment by aldrinleal** [comment]
In theory, if you set Maven Proxy, it should work. Quoting `beanstalker-common/src/main/java/br/com/ingenieux/mojo/aws/AbstractAWSMojo.java`:

```java
  protected ClientConfiguration getClientConfiguration() {
    ClientConfiguration clientConfiguration = new ClientConfiguration().withUserAgent(getUserAgent());

    if (null != this.settings && null != settings.getActiveProxy()) {
      Proxy proxy = settings.getActiveProxy();

      clientConfiguration.setProxyHost(proxy.getHost());
      clientConfiguration.setProxyUsername(proxy.getUsername());
      clientConfiguration.setProxyPassword(proxy.getPassword());
      clientConfiguration.setProxyPort(proxy.getPort());
    }

    return clientConfiguration;
  }
```

**Comment by aldrinleal** [comment]
Hit F5 on [this url](https://search.maven.org/search?q=a:beanstalker-common) until 1.5.1 appears up, which should happen in a couple of hours. :)

**Comment by marioja** [comment]
Yes I was looking at the code. The problem is that when you take the proxy user password from the maven configuration and you store it in the aws client configuration you do not first decrypt as maven does normally. This means that one cannot use maven  encrypted passwords and they must be saved in the clear

**Comment by aldrinleal** [comment]
Then check decryptpassword on [AbstractAWSMojo.java](beanstalker-common/src/main/java/br/com/ingenieux/mojo/aws/AbstractAWSMojo.java) - it should get you a good starting point. If you can find another example out there, it would be awesome, although [a perfunctory search tells me other things will break](https://bugs.eclipse.org/bugs/show_bug.cgi?id=431072)

**Comment by marioja** [comment]
The bug is for when running using m2eclipse inside eclipse. What I am talking about is more when running inside a build on something like Jenkins so cmd line

**Comment by aldrinleal** [comment]
Pull Requests are welcome :)

**Comment by marioja** [comment]
I heard that one before!

**Comment by marioja** [comment]
My problem is it is hard to test this. If you can show me how to test this maybe I could find the time. But not through github comments. Maybe phone or Skype?

**Comment by aldrinleal** [comment]
a. Checkout and import into your ide
b. Make your changes
c. `mvn clean install`
d. Pick a test project and ensure it has the right version or the plugin e.g. `1.5.2-SNAPSHOT`
e. From this test project, run `mvnDebug`
f. Attach a running debugger into this JVM
g. Loop into b.

**Comment by marioja** [comment]
As I said github comments are not optimal. I did a. in eclipse and I get errors. I do not recall exactly but I think it has to do with duplicate lifecycle mapping (which would be m2e issue) but that kind of stopped me going beyond looking at the code. Also I would have issues with e. because I use custom args to mvn and I don’t know if it would work with mvnDebug

**Comment by aldrinleal** [comment]
Give IntelliJ Idea a try :)

**Comment by marioja** [comment]
IntelliJ is not free nor can be used at work

**Comment by aldrinleal** [comment]
ok, can you care to at least test my patch if I do this change myself?

**Comment by aldrinleal** [comment]
check the `encrypted-proxy-user-and-password` branch please.

**Comment by marioja** [comment]
I will endeavor to test it today. Thanks

**Comment by marioja** [comment]
Do you use IntelliJ?

**Comment by aldrinleal** [comment]
I do. Even with a free version or licence to a pro version (and it sponsored years - based only on beanstalker), the paid version comes with support.

btw, shameless plug: http://beanstalker.ingenieux.com.br/donate.html

**Comment by marioja** [comment]
I tested the encrypted-proxy-user-and-password branch and it works flawlessly (I used the show-security-credentials goal).  It works whether the password specified in the proxy section is encrypted or not as it should.  Can we get 1.5.2 with this change?

**Comment by marioja** [comment]
Also when I ran the mvn clean install I got this error.  Do you know why and how to fix it?

```[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.2:integration-test (default-integration-test) on project elasticbeanstalk-docker-dropwizard-webapp-archetype: 
[ERROR] Archetype IT 'basic' failed: Cannot run additions goals.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:2.2:integration-test (default-integration-test) on project elasticbeanstalk-docker-dropwizard-webapp-archetype: 
Archetype IT 'basic' failed: Cannot run additions goals.
```

**Comment by aldrinleal** [comment]
> Also when I ran the mvn clean install I got this error. Do you know why and how to fix it?
> 

no, but its not critical.

**Comment by marioja** [comment]
Any chance of having the encrypted password fix in a minor version soon?

**Comment by aldrinleal** [comment]
Done

**Comment by marioja** [comment]
Thanks

**Pull request merged**
