### PR TITLE
PR for Issue 128

### PR DESCRIPTION
**Pull request by edwinquaihoi**
PR for #128

### CODE REVIEW

**Comment by aldrinleal** [comment]
Looks good to me. Thank you!

**Comment by aldrinleal** [comment]
re: JDK. Actually this week on maven-dev they were discussing bumping it to 1.8. Seems its just about time.

**Comment by edwinquaihoi** [comment]
> Looks good to me. Thank you!

No .. thank you for creating this plugin.

**Comment by aldrinleal** [comment]
Released to Central. Will be sync'ed shortly

**Pull request merged**
